@startuml The Activity Lifecycle
[*] --> onCreate 
state onCreate #green {
}
note right of onCreate
 must call setContentView 
 to define activity's user interface
end note

onCreate ---> onStart : Started state
onCreate ---> onStart : Visible to the user

note right of onStart
 - preparations for become
 - to foreground and interactive
end note

onStart ---> onResume

note left of onResume
 - call just before activity interracts with user
 - activity now on top of activitys stack
end note

onResume ---> onPause: loses focus / user leaving activity / particual visible
onPause ---> onResume

note left of onPause
 - can update UI
 - not use to save user data
 - dont network call
 - dont database transaction
end note

onPause ---> onStop: no visible to user

onStop ---> onRestart

note right of onRestart: restore activity state

onRestart ---> onStart

state onDestroy #red {
}

onStop ---> onDestroy

note right of onDestroy
 - call before destroy
 - release resources
end note

onDestroy ---> [*]
@enduml